apiVersion: v1
kind: Service
metadata:
  name: nerdzao-service
spec:
  type: NodePort
  selector:
    app: nerdzao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
